### ISSUE TITLE
 unoconv -f pdf   Fatal exception: Signal 6  libuno_sal.so.3 ubuntu 16.04

### ISSUE THREAD

**Issue by xjspace** [unoconv/unoconv#513] opened 2019-10-08 09:23 UTC
Environment:

os :ubuntu 16.04
LibreOffice 5.1.6.2
unoconv --version
unoconv 0.7
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux
python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]
LibreOffice 5.1.6.2

 unoconv -f pdf yyy.ppt

Application Error

Fatal exception: Signal 6
Stack:
/usr/lib/libreoffice/program/libuno_sal.so.3(+0x394e0)[0x7fbd06f524e0]
/usr/lib/libreoffice/program/libuno_sal.so.3(+0x39873)[0x7fbd06f52873]
/usr/lib/libreoffice/program/libuno_sal.so.3(+0x399a8)[0x7fbd06f529a8]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7fbd06b844b0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7fbd06b84428]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7fbd06b8602a]
/usr/lib/libreoffice/program/libmergedlo.so(+0x284479c)[0x7fbd099b479c]
/usr/lib/libreoffice/program/libmergedlo.so(_ZN11Application5AbortERKN3rtl8OUStringE+0x9a)[0x7fbd0990818a]
/usr/lib/libreoffice/program/libmergedlo.so(+0x186d829)[0x7fbd089dd829]
/usr/lib/libreoffice/program/libmergedlo.so(+0x279d5ee)[0x7fbd0990d5ee]
/usr/lib/libreoffice/program/libuno_sal.so.3(+0x39916)[0x7fbd06f52916]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7fbd06b844b0]
/usr/lib/libreoffice/program/libmergedlo.so(+0x27fab49)[0x7fbd0996ab49]
/usr/lib/libreoffice/program/libmergedlo.so(_ZN3vcl14OpenTTFontFileEPKcjPPNS_13_TrueTypeFontE+0x188)[0x7fbd0996b808]
/usr/lib/libreoffice/program/libmergedlo.so(_ZNK3psp16PrintFontManager19analyzeTrueTypeFileEPNS0_9PrintFontE+0x67)[0x7fbd099a78e7]
/usr/lib/libreoffice/program/libmergedlo.so(_ZNK3psp16PrintFontManager15analyzeFontFileEiRKN3rtl7OStringERNSt7__cxx114listIPNS0_9PrintFontESaIS8_EEEPKc+0x993)[0x7fbd099ac423]
/usr/lib/libreoffice/program/libmergedlo.so(_ZN3psp16PrintFontManager20countFontconfigFontsERSt13unordered_mapIN3rtl7OStringEiNS2_11OStringHashESt8equal_toIS3_ESaISt4pairIKS3_iEEE+0x535)[0x7fbd099a4d85]
/usr/lib/libreoffice/program/libmergedlo.so(_ZN3psp16PrintFontManager10initializeEv+0x164)[0x7fbd099a89c4]
/usr/lib/libreoffice/program/libmergedlo.so(_ZN3psp16PrintFontManager3getEv+0x40)[0x7fbd099a95d0]
/usr/lib/libreoffice/program/libmergedlo.so(_ZN15CairoTextRender14GetDevFontListEP22PhysicalFontCollection+0x49)[0x7fbd099d8749]
/usr/lib/libreoffice/program/libmergedlo.so(+0x263e6f9)[0x7fbd097ae6f9]
/usr/lib/libreoffice/program/libmergedlo.so(+0x2641560)[0x7fbd097b1560]
/usr/lib/libreoffice/program/libmergedlo.so(_ZNK12OutputDevice13GetTextHeightEv+0x55)[0x7fbd097b3ee5]
/usr/lib/libreoffice/program/libmergedlo.so(+0x258dc77)[0x7fbd096fdc77]
/usr/lib/libreoffice/program/libmergedlo.so(_ZN11Application11SetSettingsERK11AllSettings+0x190)[0x7fbd0990b8c0]
/usr/lib/libreoffice/program/libmergedlo.so(+0x19aedd8)[0x7fbd08b1edd8]
/usr/lib/libreoffice/program/libmergedlo.so(+0x19af9eb)[0x7fbd08b1f9eb]
/usr/lib/libreoffice/program/libmergedlo.so(+0x19b05fe)[0x7fbd08b205fe]
/usr/lib/libreoffice/program/libmergedlo.so(_ZN14SvtMiscOptionsC1Ev+0xf5)[0x7fbd08b212f5]
/usr/lib/libreoffice/program/libmergedlo.so(+0x1874c70)[0x7fbd089e4c70]
/usr/lib/libreoffice/program/libmergedlo.so(+0x279e771)[0x7fbd0990e771]
/usr/lib/libreoffice/program/libmergedlo.so(_Z6SVMainv+0x22)[0x7fbd0990e7c2]
/usr/lib/libreoffice/program/libmergedlo.so(soffice_main+0xa2)[0x7fbd08a05ec2]
/usr/lib/libreoffice/program/soffice.bin[0x4006eb]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fbd06b6f830]
/usr/lib/libreoffice/program/soffice.bin[0x400729]
Error: Unable to connect or start own listener. Aborting.

**Comment by msourada** [comment] 2020-11-11 09:31
Isn't this dupe of #306 ?

**Comment by regebro** [comment] 2021-08-13 10:34
No, it's a different one. I think this is an incorrectly installed Libreoffice, because it actually fails to start Libreoffice.
I don't think it's an unoconv issue.

**Closed** 2021-11-12 07:45 UTC
