### ISSUE TITLE
uno.RuntimeException: Binary URP bridge disposed during call

### ISSUE THREAD

**Issue by petross** [unoconv/unoconv#57] opened 2012-05-23 05:57 UTC
Hi,

I installed editors/openoffice-3 from the FreeBSD ports (Apache OpenOffice 3.4), under a recent FreeBSD-9 (Stable).

The path for pyuno.so:
/usr/local/openoffice-3.4.0/openoffice.org/basis3.4/program/pyuno.so

unoconv does not work yet.

I tried the tarball for unoconv-0.4. First I had to add in the extrapath glob.glob('/usr/local/openoffice*/openoffice.org/basis*/program')

After that it comes up with

~/unoconv-0.4/unoconv -f pdf -o ~/test.pdf ~/test.odt 
Traceback (most recent call last):
  File "/root/unoconv-0.4/unoconv", line 68, in <module>
    os.environ['LD_LIBRARY_PATH'] = oolibpath + os.pathsep + os.environ['LD_LIBRARY_PATH']
  File "/usr/local/lib/python2.7/UserDict.py", line 23, in **getitem**
    raise KeyError(key)
KeyError: 'LD_LIBRARY_PATH'

LD_LIBRARY_PATH isn't set.

Anyway, I tried to use the latest version checked out via Subversion.

~/svn/unoconv/trunk]//unoconv -f pdf -o ~/test.pdf ~/test.odt 
unoconv: Cannot find a suitable office installation on your system.
ERROR: Please locate your office installation and send your feedback to:
       http://github.com/dagwieers/unoconv/issues

I wasn't successful with the extrapath addition as I did on unoconv-04. The error stays the same (Cannot find a suitable office..)

As a side node, I replaced "#!/usr/bin/python" with "#!/usr/bin/env python" (FreeBSD installs it under /usr/local/bin).

OpenOffice 3.4 and python 2.7 are compiled at the same time (same ports snapshot from last Friday, same gcc etc.) so python and pyuno.so should fit together.

Any ideas?

Regards
Peter

**Comment by dagwieers** [comment] 2015-07-05 10:40
I am closing this ticket. if this problem still exists with the version in the master branch and a recent LibreOffice, feel free to reopen this issue. Thanks for the feedback !

**Comment by dagwieers** [comment] 2015-07-05 13:33
I am reopening this because more people are having this exact issue and there seems to be a common theme. An interesting read is this:
http://uucode.com/blog/2013/01/09/solved-createinstancewithcontext-binary-urp-bridge-disposed-during-call/

So maybe we can assume that on some platforms we may not be using the correct environment to make the python UNO bindings work correctly...

**Comment by dagwieers** [comment] 2015-07-05 13:44
Another interesting hint is in this post:
http://stackoverflow.com/questions/20554015/how-to-debug-crashing-openoffice-with-pyuno

Apparently, if something else (LogMeIn ?) is using port 2002, you get the exact same error.The easiest solution is to use another available port, eg. `-p 12345` !

This is easy to test:
```bash
[dag@moria unoconv]$ cat /dev/null | nc -l 2002 &>/dev/null &
[1] 746
[dag@moria unoconv]$ /opt/libreoffice4.0/program/python unoconv --format html --export FilterOptions=UTF8 tests/test.txt
Traceback (most recent call last):
  File "unoconv", line 1272, in <module>
    main()
  File "unoconv", line 1186, in main
    convertor = Convertor()
  File "unoconv", line 742, in __init__
    unocontext = self.connect(resolver)
  File "unoconv", line 763, in connect
    unocontext = resolver.resolve("uno:%s" % op.connection)
uno.DisposedException: Binary URP bridge disposed during call
[1]+  Done                    cat /dev/null | nc -l 2002
```
So yes, unfortunately this is a probably cause :-(

**Comment by jdgvt81** [comment] 2015-09-14 13:21
I'm running into the same problem as petross mentioned in his second comment, but running in Windows (x64 on Windows 8.1) with a 64-bit LibreOffice 5.0.1.  Running from the command prompt, here's the output:

Traceback (most recent call last):
  File "unoconv", line 1332, in <module>
    main()
  File "unoconv", line 1246, in main
    convertor = Convertor()
  File "unoconv", line 776, in __init__
    self.desktop = unosvcmgr.createInstanceWithContext("com.sun.star.frame.Desktop", unocontext)
uno.RuntimeException: Binary URP bridge disposed during call

I changed my port and still run into this issue... and the message is slightly different than in comments where the port was being blocked so I don't think that's the problem.

I edited unoconv and added a try/except around the line of code of code to print out the exact error and this is what I get:

>"C:\Program Files\LibreOffice 5\program\python.exe" unoconv -f pdf "C:\test\document-example.odt"
Binary URP bridge disposed during call
Traceback (most recent call last):
  File "unoconv", line 1335, in <module>
    main()
  File "unoconv", line 1251, in main
    convertor.convert(inputfn)
  File "unoconv", line 933, in convert
    document = self.desktop.loadComponentFromURL( inputurl , "_blank", 0, inputprops )
AttributeError: 'Convertor' object has no attribute 'desktop'

If there is anything else I can provide to help diagnose the error, please let me know.

**Comment by travcunn** [comment] 2015-10-12 14:38
Having the same issue as @jdgvt81 on 64 bit Centos 6.5 and LibreOffice 4.2.8.2

**Comment by tkhyn** [comment] 2015-11-08 01:10
Same problem here on Win7 64-bit and LibreOffice 5.0.3.2. Same setup and environment variables as @jdgvt81. Same error message.

The funny thing (which may give you some clues) ? It works perfectly on my other laptop on Win7 32-bit with LibreOffice 5.0.2.2. It also works on the same 32-bit laptop with LibreOffice 5.0.1.2 on OpenSUSE Tumbleweed.

I haven't installed OpenSUSE 64-bit on the 64bit laptop yet, but I'd expect unoconv to fail likewise. I'll know that in the next few days and keep you posted.

(and thanks heaps for your work, btw)

**Comment by adeel-raza** [comment] 2016-03-24 10:07
@dagwieers , indeed it was the issue because of the port for me. The port was used by another process and when I kill the process manually It just works fine now. Thanks a lot :)

**Comment by alexcroox** [comment] 2016-09-15 12:24
I've run `cat /dev/null | nc -l 2002 &>/dev/null &` and killed the process it returns, then I've run
`unoconv -p 12345 -f pdf -o t.pdf test.emf` but still get

```
unoconv: RuntimeException during export phase:
Office probably died. Binary URP bridge disposed during call
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1278, in <module>
    die(exitcode)
  File "/usr/bin/unoconv", line 1131, in die
    if convertor.desktop.getCurrentFrame():
uno.DisposedException: Binary URP bridge already disposed
```

**Comment by dagwieers** [comment] 2016-09-19 15:11
That command does not return the process using port 2002, it simply returns the process id (PID) of the command you just pushed in the background. So killing it is useless, not only because it is no longer running (it ends almost immediately), it is not the process using port 2002.

What you probably should be using is:
```
# lsof -iTCP:2002
```

**Comment by alexcroox** [comment] 2016-09-21 21:55
That returns no results for me, so still no idea why it wouldn't work

**Comment by regebro** [comment] 2017-10-14 13:27
Is this still an issue?

**Comment by loo41** [comment] 2018-08-15 14:10
unoconv: SystemError during import phase:
Couldn't instantiate python representation of structured UNO type com.sun.star.lang.DisposedException
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1278, in <module>
    die(exitcode)
  File "/usr/bin/unoconv", line 1131, in die
    if convertor.desktop.getCurrentFrame():
uno.DisposedException: Binary URP bridge already disposed

**Comment by eviweb** [comment] 2019-02-18 14:59
> unoconv: SystemError during import phase:
> Couldn't instantiate python representation of structured UNO type com.sun.star.lang.DisposedException
> Traceback (most recent call last):
> File "/usr/bin/unoconv", line 1278, in
> die(exitcode)
> File "/usr/bin/unoconv", line 1131, in die
> if convertor.desktop.getCurrentFrame():
> uno.DisposedException: Binary URP bridge already disposed
> 
> 怎么回事了，明明跑的好好的，几天后在跑就出现这个问题了(What's going on? Obviously running well, and running this problem in a few days.)

Hi Guys,
I just ran into the same issue as this one on unoconv version 0.8.2.
The problem came from the test `if convertor.desktop.getCurrentFrame():`.
In my case it returned `None` but in the if statement was considered as `True`.
Rewriting the test `if convertor.desktop.getCurrentFrame() is not None:` solved the issue.
For info [Python: Booleans and None - You Can't Handle the Truth!](https://amir.rachum.com/blog/2012/08/25/you-cant-handle-the-truth/).
I don't know if previous issues was related to this kind of problem, but maybe should it be checked.
Best regards

**Comment by eviweb** [comment] 2019-02-18 15:06
To be complete, here was the error message I got after the process stucked and I made a `CTRL-C`:    
```
unoconv: SystemError during update-links phase:
Couldn't instantiate python representation of structured UNO type com.sun.star.lang.DisposedException
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1408, in <module>
    die(exitcode)
  File "/usr/bin/unoconv", line 1256, in die
    if convertor.desktop.getCurrentFrame():
uno.DisposedException: Binary URP bridge already disposed
```

**Comment by regebro** [comment] 2019-02-18 17:18
"returned `None` but in the _if statement_ was considered as `True`."
Huh? It must return something very special in that case.

But you are right, that looks like it should check for is None. If someone makes a merge request, I can merge it.

**Comment by eviweb** [comment] 2019-02-20 07:30
Hi,
as testing with `is not None` solved my issue last day, it seems there is something unreliable during the communication through the URP Bridge.
Yesterday I was unable to reproduce the issue that I systematically encountered the day before.
I will continue to investigate when I will have some time to...

**Comment by acharyajay007** [comment] 2019-05-04 11:47
Anyone found any solution?
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1162, in <module>
    main()
  File "/usr/bin/unoconv", line 1079, in main
    convertor = Convertor()
  File "/usr/bin/unoconv", line 716, in __init__
    unocontext = resolver.resolve("uno:%s" % op.connection)
uno.DisposedException: Binary URP bridge disposed during call

i am still getting same error on following configuration:

unoconv 0.6
Written by Dag Wieers <dag@wieers.com>
Homepage at http://dag.wieers.com/home-made/unoconv/

platform posix/linux2
python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
LibreOffice 4.3

**Comment by eviweb** [comment] 2019-05-07 06:29
Hi,
the issue is completely unpredictable.
I've targeted two frequent break points using both unoconv and LibreOffice last versions and one document `.doc`.
The less common during the _import_ phase while calling `document = self.desktop.loadComponentFromURL( inputurl , "_blank", 0, inputprops )`, the more habitual during the _update-links_ phase while calling `document.updateLinks()`.
The origin of the problem with this document comes from an image used as background on one page, overlayed by many textfields. Both the image and the number of textfields that are positioned on it cause LibreOffice to malfunction.
From my side the issue seems to come from `soffice.bin` which creates a timeout waiting for different treatments and never get its awaited answers.
But it is not an infinite loop as `soffice.bin` is still working, and two separate runs do not permit to identify a root cause...
I doubt that the URP Bridge is in cause.
I currently did not enough investigate the unoconv side.
Unfortunately my skills in `C++` and in the use of `dbg` are close to nothing, so if someone could help me to identify the cause in LibreOffice or to find a workaround, I would appreciate ;).
Furthermore, if someone has identified a document that causes a similar issue, I'm interested to get it for testing purpose only if it does not contain any sensible data.
Best regards

**Comment by FilRav** [comment] 2019-07-27 17:33
I had the same error.  It goes away calling dispose() of XTextDocument object as soon as I ended reading the document, and setting the object to null. I also set to null all others objects of type XComponentLoader, XDesktop, XMultiServiceFactory, XComponentContext (in this order, that is reverse order with respect of initializzation sequence) when I have no more documents to read.

                xComponent = xComponentLoader.loadComponentFromURL(inputUrl, "_blank", 0, inputProps);
                xTextDocument = (XTextDocument)xComponent;
                // read xTextDocument as you like
                xTextDocument.dispose();
                xTextDocument = null;

I have all this in a loop, so exiting the loop I set to null the other objects.

**Comment by eviweb** [comment] 2019-08-26 09:19
Hi,
the problem in my case is that I never get the xComponent instance as it freezes during the call of the `loadComponentFromURL` method.

**Comment by ankur11** [comment] 2019-10-10 07:40
Hello @eviweb Did you get the solution of your problem ?

**Comment by regebro** [comment] 2021-10-04 13:29
Some more instances of this error indicates you can get this if the running LibreOffice process is a different version than the UNO library unoconv is using.

**Closed** 2021-11-12 08:37 UTC
Labels: support, FreeBSD

**Comment by vaterodev** [comment] 2025-02-14 22:01
Anyone else dealing with this issue, any fixes?
